// Auto-generated by Octave
// Array: fir_h, Samples: 40

#ifndef FIR_COEFFS_H_
#define FIR_COEFFS_H_

#include <stdint.h>

/* If you use CMSIS-DSP, include "arm_math.h" or "cmsis_dsp.h" instead. */
#ifndef __FLOAT32_T_DEFINED
#define __FLOAT32_T_DEFINED
typedef float float32_t;
#endif

/* FIR design metadata */
static const uint32_t fir_h_taps  = 40;
static const uint32_t fir_h_order = 39;
static const float32_t fir_h_fs_hz  = 44100f;
static const float32_t fir_h_fc1_hz = 19000f;
static const float32_t fir_h_fc2_hz = 0f; /* unused */
/* type=lowpass, window=hamming, beta=8.000, normalize=1 */

static const float32_t fir_h[40] = {
  0.000757790927f, -0.000272106641f, -0.000464868761f, 0.00161574199f, -0.00317860465f, 0.00485364441f, -0.00600290904f, 0.00574720697f, 
  -0.00320280157f, -0.00218722341f, 0.0103106787f, -0.0201319512f, 0.029606808f, -0.035794083f, 0.0351014361f, -0.0234512724f, 
  -0.00420638639f, 0.0570563264f, -0.16628401f, 0.620126605f, 0.620126605f, -0.16628401f, 0.0570563264f, -0.00420638639f, 
  -0.0234512724f, 0.0351014361f, -0.035794083f, 0.029606808f, -0.0201319512f, 0.0103106787f, -0.00218722341f, -0.00320280157f, 
  0.00574720697f, -0.00600290904f, 0.00485364441f, -0.00317860465f, 0.00161574199f, -0.000464868761f, -0.000272106641f, 0.000757790927f
};

#endif // FIR_COEFFS_H_
